# docker-compose.yml
version: '3.8'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: vacation-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_FILE=./data.sqlite
      - JWT_SECRET=supersecret
    volumes:
      - ./server:/app
      - ./server/data.sqlite:/app/data.sqlite

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vacation-web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./client:/app
    depends_on:
      - api
